"""List of Daz bone names and the corresponding rigify deformation bone name"""


vg_names = {
    'lToe': None,
    'rToe': None,
    'hip': None,

    # Torso
    # Spine
    'pelvis': 'DEF-spine',
    'abdomenLower': 'DEF-spine.001',
    'abdomenUpper': 'DEF-spine.001.2',
    'chestLower': 'DEF-spine.002',
    'chestUpper': 'DEF-spine.003',
    # Neck/Head
    'neckLower': 'DEF-spine.004',
    'neckUpper': 'DEF-spine.005',
    'head': 'DEF-spine.006',
    # Chest
    'lPectoral': 'DEF-breast.L',
    'rPectoral': 'DEF-breast.R',
    # Arms
    # Upper
    'lCollar': 'DEF-shoulder.L',
    'rCollar': 'DEF-shoulder.R',
    'lShldrBend': 'DEF-upper_arm.L',
    'rShldrBend': 'DEF-upper_arm.R',
    'lShldrTwist': 'DEF-upper_arm.L.001',
    'rShldrTwist': 'DEF-upper_arm.R.001',
    'lForearmBend': 'DEF-forearm.L',
    'rForearmBend': 'DEF-forearm.R',
    'lForearmTwist': 'DEF-forearm.L.001',
    'rForearmTwist': 'DEF-forearm.R.001',
    # Hands
    'lHand': 'DEF-hand.L',
    'rHand': 'DEF-hand.R',
    'lCarpal1': 'DEF-palm.01.L',
    'rCarpal1': 'DEF-palm.01.R',
    'lCarpal2': 'DEF-palm.02.L',
    'rCarpal2': 'DEF-palm.02.R',
    'lCarpal3': 'DEF-palm.03.L',
    'rCarpal3': 'DEF-palm.03.R',
    'lCarpal4': 'DEF-palm.04.L',
    'rCarpal4': 'DEF-palm.04.R',
    # Fingers
    # Thumb
    'lThumb1': 'DEF-thumb.01.L',
    'rThumb1': 'DEF-thumb.01.R',
    'lThumb2': 'DEF-thumb.02.L',
    'rThumb2': 'DEF-thumb.02.R',
    'lThumb3': 'DEF-thumb.03.L',
    'rThumb3': 'DEF-thumb.03.R',
    # Index
    'lIndex1': 'DEF-f_index.01.L',
    'rIndex1': 'DEF-f_index.01.R',
    'lIndex2': 'DEF-f_index.02.L',
    'rIndex2': 'DEF-f_index.02.R',
    'lIndex3': 'DEF-f_index.03.L',
    'rIndex3': 'DEF-f_index.03.R',
    # Middle
    'lMid1': 'DEF-f_middle.01.L',
    'rMid1': 'DEF-f_middle.01.R',
    'lMid2': 'DEF-f_middle.02.L',
    'rMid2': 'DEF-f_middle.02.R',
    'lMid3': 'DEF-f_middle.03.L',
    'rMid3': 'DEF-f_middle.03.R',
    # Ring
    'lRing1': 'DEF-f_ring.01.L',
    'rRing1': 'DEF-f_ring.01.R',
    'lRing2': 'DEF-f_ring.02.L',
    'rRing2': 'DEF-f_ring.02.R',
    'lRing3': 'DEF-f_ring.03.L',
    'rRing3': 'DEF-f_ring.03.R',
    # Pinky
    'lPinky1': 'DEF-f_pinky.01.L',
    'rPinky1': 'DEF-f_pinky.01.R',
    'lPinky2': 'DEF-f_pinky.02.L',
    'rPinky2': 'DEF-f_pinky.02.R',
    'lPinky3': 'DEF-f_pinky.03.L',
    'rPinky3': 'DEF-f_pinky.03.R',
    # Legs
    # Upper
    'lThighBend': 'DEF-thigh.L',
    'rThighBend': 'DEF-thigh.R',
    'lThighTwist': 'DEF-thigh.L.001',
    'rThighTwist': 'DEF-thigh.R.001',
    'lShin': 'DEF-shin.L',
    'rShin': 'DEF-shin.R',
    # Foot
    'lFoot': 'DEF-foot.L',
    'rFoot': 'DEF-foot.R',
    'lMetatarsals': 'DEF-foot.L',
    'rMetatarsals': 'DEF-foot.R',
    'lHeel': 'DEF-foot.L',
    'rHeel': 'DEF-foot.R',
    # Toes
    # Big
    'lBigToe': 'DEF-toe1.01.L',
    'rBigToe': 'DEF-toe1.01.R',
    'lBigToe_2': 'DEF-toe1.02.L',
    'rBigToe_2': 'DEF-toe1.02.R',
    # Long
    'lSmallToe1': 'DEF-toe2.01.L',
    'rSmallToe1': 'DEF-toe2.01.R',
    'lSmallToe1_2': 'DEF-toe2.03.L',
    'rSmallToe1_2': 'DEF-toe2.03.R',
    # Middle
    'lSmallToe2': 'DEF-toe3.01.L',
    'rSmallToe2': 'DEF-toe3.01.R',
    'lSmallToe2_2': 'DEF-toe3.03.L',
    'rSmallToe2_2': 'DEF-toe3.03.R',
    # Ring
    'lSmallToe3': 'DEF-toe4.01.L',
    'rSmallToe3': 'DEF-toe4.01.R',
    'lSmallToe3_2': 'DEF-toe4.03.L',
    'rSmallToe3_2': 'DEF-toe4.03.R',
    # Pinky
    'lSmallToe4': 'DEF-toe5.01.L',
    'rSmallToe4': 'DEF-toe5.01.R',
    'lSmallToe4_2': 'DEF-toe5.03.L',
    'rSmallToe4_2': 'DEF-toe5.03.R',

    # Penis
    'Shaft 1': 'DEF-shaft.01',
    'Shaft 2': 'DEF-shaft.02',
    'Shaft 3': 'DEF-shaft.03',
    'Shaft 4': 'DEF-shaft.04',
    'Shaft5': 'DEF-shaft.05',
    'Shaft 5': 'DEF-shaft.05',
    'Shaft 6': 'DEF-shaft.06',
    'Shaft 7': 'DEF-shaft.07',
    'Scortum': 'DEF-scrotum',
    'Left Testicle': 'DEF-testicle.L',
    'Right Testicle': 'DEF-testicle.R',

    # Face
    # # Maybe use later
    # 'upperTeeth': 'DEF-spine.006',
    # 'lowerJaw': 'DEF-spine.006',
    # 'lowerTeeth': 'DEF-spine.006',
    # 'tongue01': 'DEF-spine.006',
    # 'tongue02': 'DEF-spine.006',
    # 'tongue03': 'DEF-spine.006',
    # 'tongue04': 'DEF-spine.006',
    # 'lNasolabialLower': 'DEF-spine.006',
    # 'rNasolabialLower': 'DEF-spine.006',
    # 'lNasolabialMouthCorner': 'DEF-spine.006',
    # 'rNasolabialMouthCorner': 'DEF-spine.006',
    # 'lLipCorner': 'DEF-spine.006',
    # 'lLipLowerOuter': 'DEF-spine.006',
    # 'lLipLowerInner': 'DEF-spine.006',
    # 'LipLowerMiddle': 'DEF-spine.006',
    # 'rLipLowerInner': 'DEF-spine.006',
    # 'rLipLowerOuter': 'DEF-spine.006',
    # 'rLipCorner': 'DEF-spine.006',
    # 'LipBelow': 'DEF-spine.006',
    # 'Chin': 'DEF-spine.006',
    # 'lCheekLower': 'DEF-spine.006',
    # 'rCheekLower': 'DEF-spine.006',
    # 'BelowJaw': 'DEF-spine.006',
    # 'lJawClench': 'DEF-spine.006',
    # 'rJawClench': 'DEF-spine.006',
    # 'rBrowInner': 'DEF-spine.006',
    # 'rBrowMid': 'DEF-spine.006',
    # 'rBrowOuter': 'DEF-spine.006',
    # 'lBrowInner': 'DEF-spine.006',
    # 'lBrowMid': 'DEF-spine.006',
    # 'lBrowOuter': 'DEF-spine.006',
    # 'CenterBrow': 'DEF-spine.006',
    # 'MidNoseBridge': 'DEF-spine.006',
    # 'lEyelidInner': 'DEF-spine.006',
    # 'lEyelidUpperInner': 'DEF-spine.006',
    # 'lEyelidUpper': 'DEF-spine.006',
    # 'lEyelidUpperOuter': 'DEF-spine.006',
    # 'lEyelidOuter': 'DEF-spine.006',
    # 'lEyelidLowerOuter': 'DEF-spine.006',
    # 'lEyelidLower': 'DEF-spine.006',
    # 'lEyelidLowerInner': 'DEF-spine.006',
    # 'rEyelidInner': 'DEF-spine.006',
    # 'rEyelidUpperInner': 'DEF-spine.006',
    # 'rEyelidUpper': 'DEF-spine.006',
    # 'rEyelidUpperOuter': 'DEF-spine.006',
    # 'rEyelidOuter': 'DEF-spine.006',
    # 'rEyelidLowerOuter': 'DEF-spine.006',
    # 'rEyelidLower': 'DEF-spine.006',
    # 'rEyelidLowerInner': 'DEF-spine.006',
    # 'lSquintInner': 'DEF-spine.006',
    # 'lSquintOuter': 'DEF-spine.006',
    # 'rSquintInner': 'DEF-spine.006',
    # 'rSquintOuter': 'DEF-spine.006',
    # 'lCheekUpper': 'DEF-spine.006',
    # 'rCheekUpper': 'DEF-spine.006',
    # 'Nose': 'DEF-spine.006',
    # 'lNostril': 'DEF-spine.006',
    # 'rNostril': 'DEF-spine.006',
    # 'lLipBelowNose': 'DEF-spine.006',
    # 'rLipBelowNose': 'DEF-spine.006',
    # 'lLipUpperOuter': 'DEF-spine.006',
    # 'lLipUpperInner': 'DEF-spine.006',
    # 'LipUpperMiddle': 'DEF-spine.006',
    # 'rLipUpperInner': 'DEF-spine.006',
    # 'rLipUpperOuter': 'DEF-spine.006',
    # 'lLipNasolabialCrease': 'DEF-spine.006',
    # 'rLipNasolabialCrease': 'DEF-spine.006',
    # 'lNasolabialUpper': 'DEF-spine.006',
    # 'rNasolabialUpper': 'DEF-spine.006',
    # 'lNasolabialMiddle': 'DEF-spine.006',
    # 'rNasolabialMiddle': 'DEF-spine.006',
    # 'lEye': 'DEF-spine.006',
    # 'rEye': 'DEF-spine.006',
    # 'lEar': 'DEF-spine.006',
    # 'rEar': 'DEF-spine.006',
}
